# Generated by Django 5.1.3 on 2025-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
