# Generated by Django 5.1.3 on 2025-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="age",
            field=models.IntegerField(blank=True),
        ),
    ]
