# Generated by Django 5.1.3 on 2025-01-29 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0002_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="slug",
        ),
    ]
