# Generated by Django 5.1.3 on 2025-01-31 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0002_alter_studentprofile_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="age",
        ),
    ]
