# Generated by Django 5.1.3 on 2025-01-29 15:39

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0003_remove_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="logo",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.filesystem.FileSystemStorage,
                upload_to="",
            ),
        ),
    ]
