# Generated by Django 5.1.3 on 2025-01-29 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0004_course_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="logo",
            new_name="image",
        ),
    ]
