# Generated by Django 5.1.3 on 2025-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0005_remove_studentprofile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="future_teachers",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
