# Generated by Django 5.1.3 on 2025-01-31 21:40

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0006_course_future_teachers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=django.core.files.storage.filesystem.FileSystemStorage,
                        upload_to="",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="files/")),
            ],
        ),
    ]
