# Generated by Django 5.1.3 on 2025-01-30 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edu", "0007_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
