# Generated by Django 5.1.3 on 2024-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("certificate_image", models.ImageField(upload_to="certificates/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
