# Generated by Django 5.1.3 on 2024-11-28 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_certificate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
