name: rpi Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: |
          # stop anything running on port 8080
          sudo fuser -k 8080/tcp || true

          # Set up virtual environment
          python -m venv /home/belix/dev/oasis
          source /home/belix/dev/oasis/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py makemigrations edu
          python manage.py migrate
          # Restart the systemd service to persist Django
          sudo systemctl restart oasis
          
          # Show service status (for debugging)
          sudo systemctl status oasis --no-pager
