name: rpi Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo fuser -k 8080/tcp || true
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py runserver 8080 &
