name: rpi Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: |
          
          sudo fuser -k 8080/tcp || true
          cd /home/belix/actions-runner/_worker/oasis-hackathon/oasis-hackathon

          # Set up virtual environment
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

          # Restart the systemd service to persist Django
          sudo systemctl restart oasis
          
          # Show service status (for debugging)
          sudo systemctl status oasis --no-pager
